---
name: trekax
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^2.12.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: null
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter_spinkit: ^5.0.0
  geolocator: null
  overlay_support: ^1.2.1
  flutter_polyline_points:
  flutter_google_places: null
  google_maps_webservice: null
  geocoding: null
  google_maps_flutter: null
  shared_preferences: ^2.0.5
  uuid: null
  http: null
  url_launcher: null
  get: ^4.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
